services:
  verbaquest-db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - PG_LOG_DESTINATION=stderr
      - PG_LOG_STATEMENT=all
    ports:
      - "5433:5432"
    networks:
      - verbaquest
  
  backend:
    depends_on:
      - verbaquest-db
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    env_file:
      - ./packages/api/docker.env
    ports:
      - "5001:5001"
    networks:
      - verbaquest

  frontend:
    build:
      context: ./packages/web-frontend
      dockerfile: Dockerfile
    env_file:
      - ./packages/web-frontend/docker.env
    depends_on:
      - backend
      - verbaquest-db
    ports:
      - "8080:8080"
    networks:
      - verbaquest


networks:
  verbaquest:

volumes:
  verbaquest_data: